# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

g <- function(x) {
    .Call(`_TobitTest_g`, x)
}

h <- function(x) {
    .Call(`_TobitTest_h`, x)
}

elln <- function(y1, r0, r1, gamma, left = 0) {
    .Call(`_TobitTest_elln`, y1, r0, r1, gamma, left)
}

elln_prime <- function(x0j, x1j, y1, r0, r1, gamma, left = 0) {
    .Call(`_TobitTest_elln_prime`, x0j, x1j, y1, r0, r1, gamma, left)
}

tobitADMM_C <- function(x, yin, left, Cin, M, Mc, tin, a, lambda, rho, delta_init, gamma_init, eta_init, nu1_init, nu2_init, abs_tol, rel_tol, nr_tol, theta_tol, full_model, maxit) {
    .Call(`_TobitTest_tobitADMM_C`, x, yin, left, Cin, M, Mc, tin, a, lambda, rho, delta_init, gamma_init, eta_init, nu1_init, nu2_init, abs_tol, rel_tol, nr_tol, theta_tol, full_model, maxit)
}

LprimeC <- function(xj, y, d, r, gamma) {
    .Call(`_TobitTest_LprimeC`, xj, y, d, r, gamma)
}

logL1 <- function(y, d, r, gamma) {
    .Call(`_TobitTest_logL1`, y, d, r, gamma)
}

tobitnet_innerC <- function(xin, yin, cin, lambda1, lambda2, pf1, pf2, delta_init, delta_0_init = 0, gamma_init = 1, eps = 1e-7, standardize = TRUE, maxit = 1e6) {
    .Call(`_TobitTest_tobitnet_innerC`, xin, yin, cin, lambda1, lambda2, pf1, pf2, delta_init, delta_0_init, gamma_init, eps, standardize, maxit)
}

